# Generated by Django 3.2.5 on 2021-07-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidtest',
            old_name='user',
            new_name='user_id',
        ),
    ]
